repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
        -
            id: end-of-file-fixer
            exclude: |
                \.json$
                \.yaml$
                \.yml$
        -
            id: trailing-whitespace
            exclude: |
                \.md$
                \.yaml$
                \.yml$
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.2
    hooks:
    -   id: ruff
        types: [python]
        args: [-V, --verbose, --ignore=D102, --fix, --config=./backend/pyproject.toml]
    -   id: ruff-format
        types: [python]
-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
    -   id: gitleaks
