repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
        -
            id: end-of-file-fixer
            exclude: |
                \.json$
                \.yaml$
                \.yml$
        -
            id: trailing-whitespace
            exclude: |
                \.md$
                \.yaml$
                \.yml$
-   repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
    -   id: black
        types: [python]
        language_version: python3.12
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.3.2
    hooks:
    -   id: ruff
        types: [python]
        args: [--ignore=D102]
-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
    -   id: gitleaks
