repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
        -
            id: end-of-file-fixer
            exclude: |
                \.json$
                \.yaml$
                \.yml$
        -
            id: trailing-whitespace
            exclude: \.md$
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        types: [python]
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.5
    hooks:
    -   id: ruff
        types: [python]
        args: [--ignore=D102]
