site_name: KWAI
site_description: kwai, the sports club management system
site_dir: ./_site

nav:
  - Intro: 'index.md'
  - Backend: '!include ./backend/mkdocs.yml'
  - Frontend: '!include ./frontend/mkdocs.yml'

theme:
  name: "material"
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    accent: blue
    toggle:
      icon: material/lightbulb
      name: Switch to light mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    accent: blue
    toggle:
      icon: material/lightbulb-outline
      name: Switch to dark mode

repo_name: zumuta/kwai
repo_url: https://codeberg.org/zumuta/kwai

extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - admonition
  - codehilite

plugins:
  - monorepo
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: ['./backend/src']
          options:
            show_root_heading: true
            show_source: false
            docstring_style: google
            show_root_toc_entry: true
watch:
  - backend/src
