# Rename this file to kwai.toml and set the env KWAI_SETTINGS_FILE to the path of this file.
[frontend]
test = false
path = ""  # Where are the frontend applications deployed?

[[frontend.apps]]
name = "portal"
default = true
vite_server = "http://localhost:3000/apps/portal"  # Only necessary in test mode

[[frontend.apps]]
name = "author"
vite_server = "http://localhost:3001/apps/author"  # Only necessary in test mode

[[frontend.apps]]
name = "auth"
vite_server="http://localhost:3002/apps/auth"  # Only necessary in test mode

[[frontend.apps]]
name = "coach"
vite_server="http://localhost:3003/apps/coach"  # Only necessary in test mode

[[frontend.apps]]
name = "club"
vite_server="http://localhost:3004/apps/club"  # Only necessary in test mode

[files]
path="/var/tmp/kwai"

[security]
access_token_expires_in=60  # 60 minutes
refresh_token_expires_in=43200  # 30 days
jwt_algorithm="HS256"
jwt_secret=""
jwt_refresh_secret=""

[cors]
origins=[]
headers=["*"] # All
methods=["*"] # All

[logger]
file="kwai.log"

[db]
host=""
name=""
user=""
password=""

[template]
path=""

[website]
url=""
email=""
name=""

[email]
host=""
port=2525
password=""
user=""
from=""

[redis]
host=""
port=6379
password=""

[redis.logger]
file="kwai.redis.log"
