site_name: kwai backend
site_description: kwai backend, the API for the sports club management system.
docs_dir: docs

nav:
  - Intro: index.md
  - source: core/index.md
  - Modules: modules/index.md
  - api:
    - auth: api/api_auth.md
