site_name: kwai backend
site_description: kwai backend, the API for the sports club management system.
docs_dir: docs

nav:
  - index.md
  - API:
    - auth: api/api_auth.md
  - cli.md
  - source.md
  - modules/index.md
