site_name: kwai backend
site_description: kwai backend, the API for the sports club management system.
docs_dir: docs

nav:
  - index.md
  - architecture.md
  - api/index.md
  - cli.md
  - source.md
  - deploy.md
  - modules/index.md
  - reference.md
