-- migrate:up

-- seeding countries table
-- downloaded from https://stefangabos.github.io/world_countries/
insert ignore into countries(iso_2, iso_3, name) values
("AF", "AFG", "Afghanistan"),
("AL", "ALB", "Albanië"),
("DZ", "DZA", "Algerije"),
("AD", "AND", "Andorra"),
("AO", "AGO", "Angola"),
("AG", "ATG", "Antigua en Barbuda"),
("AR", "ARG", "Argentinië"),
("AM", "ARM", "Armenië"),
("AU", "AUS", "Australië"),
("AZ", "AZE", "Azerbeidzjan"),
("BS", "BHS", "Bahama's"),
("BH", "BHR", "Bahrein"),
("BD", "BGD", "Bangladesh"),
("BB", "BRB", "Barbados"),
("BE", "BEL", "België"),
("BZ", "BLZ", "Belize"),
("BJ", "BEN", "Benin"),
("BT", "BTN", "Bhutan"),
("BO", "BOL", "Bolivia"),
("BA", "BIH", "Bosnië en Herzegovina"),
("BW", "BWA", "Botswana"),
("BR", "BRA", "Brazilië"),
("BN", "BRN", "Brunei"),
("BG", "BGR", "Bulgarije"),
("BF", "BFA", "Burkina Faso"),
("BI", "BDI", "Burundi"),
("KH", "KHM", "Cambodja"),
("CA", "CAN", "Canada"),
("CF", "CAF", "Centraal-Afrikaanse Republiek"),
("CL", "CHL", "Chili"),
("CN", "CHN", "China"),
("CO", "COL", "Colombia"),
("KM", "COM", "Comoren"),
("CG", "COG", "Congo-Brazzaville"),
("CD", "COD", "Congo-Kinshasa"),
("CR", "CRI", "Costa Rica"),
("CU", "CUB", "Cuba"),
("CY", "CYP", "Cyprus"),
("DK", "DNK", "Denemarken"),
("DJ", "DJI", "Djibouti"),
("DM", "DMA", "Dominica"),
("DO", "DOM", "Dominicaanse Republiek"),
("DE", "DEU", "Duitsland"),
("EC", "ECU", "Ecuador"),
("EG", "EGY", "Egypte"),
("SV", "SLV", "El Salvador"),
("GQ", "GNQ", "Equatoriaal-Guinea"),
("ER", "ERI", "Eritrea"),
("EE", "EST", "Estland"),
("ET", "ETH", "Ethiopië"),
("FJ", "FJI", "Fiji"),
("PH", "PHL", "Filipijnen"),
("FI", "FIN", "Finland"),
("FR", "FRA", "Frankrijk"),
("GA", "GAB", "Gabon"),
("GM", "GMB", "Gambia"),
("GE", "GEO", "Georgië"),
("GH", "GHA", "Ghana"),
("GD", "GRD", "Grenada"),
("GR", "GRC", "Griekenland"),
("GT", "GTM", "Guatemala"),
("GN", "GIN", "Guinee"),
("GW", "GNB", "Guinee-Bissau"),
("GY", "GUY", "Guyana"),
("HT", "HTI", "Haïti"),
("HN", "HND", "Honduras"),
("HU", "HUN", "Hongarije"),
("IE", "IRL", "Ierland"),
("IS", "ISL", "IJsland"),
("IN", "IND", "India"),
("ID", "IDN", "Indonesië"),
("IQ", "IRQ", "Irak"),
("IR", "IRN", "Iran"),
("IL", "ISR", "Israël"),
("IT", "ITA", "Italië"),
("CI", "CIV", "Ivoorkust"),
("JM", "JAM", "Jamaica"),
("JP", "JPN", "Japan"),
("YE", "YEM", "Jemen"),
("JO", "JOR", "Jordanië"),
("CV", "CPV", "Kaapverdië"),
("CM", "CMR", "Kameroen"),
("KZ", "KAZ", "Kazachstan"),
("KE", "KEN", "Kenia"),
("KG", "KGZ", "Kirgizië"),
("KI", "KIR", "Kiribati"),
("KW", "KWT", "Koeweit"),
("HR", "HRV", "Kroatië"),
("LA", "LAO", "Laos"),
("LS", "LSO", "Lesotho"),
("LV", "LVA", "Letland"),
("LB", "LBN", "Libanon"),
("LR", "LBR", "Liberia"),
("LY", "LBY", "Libië"),
("LI", "LIE", "Liechtenstein"),
("LT", "LTU", "Litouwen"),
("LU", "LUX", "Luxemburg"),
("MG", "MDG", "Madagaskar"),
("MW", "MWI", "Malawi"),
("MV", "MDV", "Malediven"),
("MY", "MYS", "Maleisië"),
("ML", "MLI", "Mali"),
("MT", "MLT", "Malta"),
("MA", "MAR", "Marokko"),
("MH", "MHL", "Marshalleilanden"),
("MR", "MRT", "Mauritanië"),
("MU", "MUS", "Mauritius"),
("MX", "MEX", "Mexico"),
("FM", "FSM", "Micronesië"),
("MD", "MDA", "Moldavië"),
("MC", "MCO", "Monaco"),
("MN", "MNG", "Mongolië"),
("ME", "MNE", "Montenegro"),
("MZ", "MOZ", "Mozambique"),
("MM", "MMR", "Myanmar"),
("NA", "NAM", "Namibië"),
("NR", "NRU", "Nauru"),
("NL", "NLD", "Nederland"),
("NP", "NPL", "Nepal"),
("NI", "NIC", "Nicaragua"),
("NZ", "NZL", "Nieuw-Zeeland"),
("NE", "NER", "Niger"),
("NG", "NGA", "Nigeria"),
("KP", "PRK", "Noord-Korea"),
("MK", "MKD", "Noord-Macedonië"),
("NO", "NOR", "Noorwegen"),
("UG", "UGA", "Oeganda"),
("UA", "UKR", "Oekraïne"),
("UZ", "UZB", "Oezbekistan"),
("OM", "OMN", "Oman"),
("AT","AUT","Oostenrijk"),
("TL","TLS","Oost-Timor"),
("PK","PAK","Pakistan"),
("PW","PLW","Palau"),
("PA","PAN","Panama"),
("PG","PNG","Papoea-Nieuw-Guinea"),
("PY","PRY","Paraguay"),
("PE","PER","Peru"),
("PL","POL","Polen"),
("PT","PRT","Portugal"),
("QA","QAT","Qatar"),
("RO","ROU","Roemenië"),
("RU","RUS","Rusland"),
("RW","RWA","Rwanda"),
("KN","KNA","Saint Kitts en Nevis"),
("LC","LCA","Saint Lucia"),
("VC","VCT","Saint Vincent en de Grenadines"),
("SB", "SLB", "Salomonseilanden"),
("WS", "WSM", "Samoa"),
("SM", "SMR", "San Marino"),
("SA", "SAU", "Saoedi-Arabië"),
("ST", "STP", "Sao Tomé en Principe"),
("SN", "SEN", "Senegal"),
("RS", "SRB", "Servië"),
("SC", "SYC", "Seychellen"),
("SL", "SLE", "Sierra Leone"),
("SG", "SGP", "Singapore"),
("SI", "SVN", "Slovenië"),
("SK", "SVK", "Slowakije"),
("SD", "SDN", "Soedan"),
("SO", "SOM", "Somalië"),
("ES", "ESP", "Spanje"),
("LK", "LKA", "Sri Lanka"),
("SR", "SUR", "Suriname"),
("SZ", "SWZ", "Swaziland"),
("SY", "SYR", "Syrië"),
("TJ", "TJK", "Tadzjikistan"),
("TZ", "TZA", "Tanzania"),
("TH", "THA", "Thailand"),
("TG", "TGO", "Togo"),
("TO", "TON", "Tonga"),
("TT", "TTO", "Trinidad en Tobago"),
("TD", "TCD", "Tsjaad"),
("CZ", "CZE", "Tsjechië"),
("TN", "TUN", "Tunesië"),
("TR", "TUR", "Turkije"),
("TM", "TKM", "Turkmenistan"),
("TV", "TUV", "Tuvalu"),
("UY", "URY", "Uruguay"),
("VU", "VUT", "Vanuatu"),
("VE", "VEN", "Venezuela"),
("AE", "ARE", "Verenigde Arabische Emiraten"),
("US", "USA", "Verenigde Staten"),
("GB", "GBR", "Verenigd Koninkrijk"),
("VN", "VNM", "Vietnam"),
("BY", "BLR", "Wit-Rusland"),
("ZM", "ZMB", "Zambia"),
("ZW", "ZWE", "Zimbabwe"),
("ZA", "ZAF", "Zuid-Afrika"),
("KR", "KOR", "Zuid-Korea"),
("SS", "SSD", "Zuid-Soedan"),
("SE", "SWE", "Zweden"),
("CH", "CHE", "Zwitserland")

-- migrate:down
