fail_fast: true

repos:
  - repo: https://github.com/ambv/black
    rev: 22.12.0
    hooks:
      - id: black

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.138
    hooks:
      - id: ruff
        args:
        - --fix
