[website]
title = ""
copyright = ""
email = ""
url = ""

[portal]
promotion = [
    ""
]
[[portal.social_media]]
title = ""
account = ""
icon = ""
url = ""
text = ""

[[portal.links]]
title = ""
url = ""

[api]
base_url = ""
