[website]
title = ""
copyright = ""
email = ""
url = ""

[contact]
street = ""
city = ""
email = ""

[portal]
promotion = [
    ""
]
promotion_footer = [
    ""
]

[[portal.social_media]]
title = ""
account = ""
icon = ""
url = ""
text = ""

[[portal.links]]
title = ""
url = ""

[api]
base_url = ""
