name: sphinx

on:
  push:
    tags: '*'
  pull_request:
    branches:
      - master
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - uses: snok/install-poetry@v1
    - name: install
      run: poetry install
    - name: Build documentation
      run: |
        mkdir -p gh-pages/backend
        touch gh-pages/.nojekyll
        cd backend/src
        poetry run sphinx-apidoc -o ../docs/kwai ./kwai
        poetry run sphinx-apidoc -o ../docs/tests ./tests
        cd backend/docs
        make html
        cp -r _build/* ../../gh-pages/backend        
    - name: Deploy documentation
      if: ${{ github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: gh-pages
