name: generate docs

on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install Poetry
      run: pip install poetry
    - name: install
      working-directory: backend
      run: poetry install --with docs
    - name: Build documentation
      working-directory: backend
      run: |
        poetry run mkdocs build -f ../mkdocs.yml
    - name: Copy site
      run: |
        mkdir -p gh-pages
        touch gh-pages/.nojekyll
        cp -r _site/* gh-pages
    - name: Deploy documentation
      if: ${{ github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@v4.7.3
      with:
        branch: gh-pages
        folder: gh-pages
        clean-exclude: |
          coverage/*
