name: mkdocs

on:
  push:
    branches:
      - master
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - uses: snok/install-poetry@v1
    - name: install
      run: poetry install
    - name: Build documentation
      run: |
        mkdir -p gh-pages
        touch gh-pages/.nojekyll
        cd backend/src
        poetry run mkdocs build -f ../../mkdocs.yml
        cd ../..
        cp -r _site/* ../../gh-pages
    - name: Deploy documentation
      if: ${{ github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: gh-pages
