name: ruff
on:
  push:
    paths:
    - "backend/src/**"
  pull_request:
    paths:
    - "backend/src/**"
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v1
        with:
          src: "${{ github.workspace }}/backend/src"
          args: --ignore D102
