name: Ruff
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
        with:
          src: "${{ GITHUB_WORKSPACE }}/backend/src"
          args: --config "${{ GITHUB_WORKSPACE }}/backend/pyproject.toml" --ignore D102
