name: ruff
on:
  push:
    paths:
    - "backend/src/**"
  pull_request:
    paths:
    - "backend/src/**"
  workflow_dispatch:
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          version: "latest"
          src: "${{ github.workspace }}/backend/src"
          args: check --verbose --ignore D102 --config ${{ github.workspace }}/backend/pyproject.toml
