name: Ruff
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: ls -lart
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
        with:
          src: "./backend/src"
          args: --config "./backend/pyproject.toml" --ignore D102
